language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
env: DB=mysql
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/github.yml.example config/github.yml"
  - "cp config/mailers.yml.example config/mailers.yml"
  - "cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
